apiVersion: v1
kind: Namespace
metadata:
  name: graylog
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  selector:
    app: db
  ports:
    - protocol: UDP
      name: udp-graylog
      port: 12201
