apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grafana
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-istio
        protocol: HTTP
      hosts:
        - 'grafana.local'
        - 'kiali.local'
        - 'prometheus.local'
        - 'jaeger.local'

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: istio-system
spec:
  hosts:
    - 'grafana.local'
  gateways:
    - istio-system/grafana
  http:
    - route:
        - destination:
            port:
              number: 3000
            host: grafana

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
  namespace: istio-system
spec:
  hosts:
    - 'kiali.local'
  gateways:
    - istio-system/grafana
  http:
    - route:
        - destination:
            port:
              number: 20001
            host: kiali

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jaeger
  namespace: istio-system
spec:
  hosts:
    - 'jaeger.local'
  gateways:
    - istio-system/grafana
  http:
    - route:
        - destination:
            port:
              number: 80
            host: tracing

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system
spec:
  hosts:
    - 'prometheus.local'
  gateways:
    - istio-system/grafana
  http:
    - route:
        - destination:
            port:
              number: 9090
            host: prometheus
