apiVersion: apps/v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userse
  template:
    metadata:
      labels:
        app: usersa
    spec:
      containers:
        - name: users-ms
          image: users-ms:0.0.1
          ports:
            - containerPort: 80
#ADD CONFIGS!!

---
apiVersion: v1
kind: Service
metadata:
  name: www
  namespace: users
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: www-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - 'users.local'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: www
spec:
  hosts:
    - 'users.local'
  gateways:
    - www-gateway
  http:
    - route:
        - destination:
            host: www.users
