apiVersion: v1
kind: Namespace
metadata:
  name: mailer
  labels:
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: mailer
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-mailer
        protocol: HTTP
      hosts:
        - 'mailer.local'
