apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: node
          image: docker.pkg.github.com/w473/mailing-microservice/mailing-ms:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: app-mailing-config
            - secretRef:
                name: app-config
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: webhost
  namespace: mailer
spec:
  selector:
    app: mailer
  ports:
    - protocol: TCP
      name: tcp-app
      port: 80

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: www
  namespace: mailer
spec:
  hosts:
    - 'mailer.local'
  gateways:
    - gateway
  http:
    - route:
        - destination:
            host: webhost
